# Generated by Django 5.2 on 2025-05-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=40, unique=True, verbose_name='Titulo de la noticia')),
                ('Parrafo', models.CharField(max_length=1000, unique=True, verbose_name='Titulo de la noticia')),
                ('Fecha_Publicacion', models.DateField(verbose_name='Fecha de publicacion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Noticia/')),
            ],
        ),
    ]
