# Generated by Django 5.2 on 2025-05-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='Parrafo',
            field=models.CharField(max_length=10000, unique=True, verbose_name='Contenido de la Noticia'),
        ),
    ]
