# Generated by Django 5.1.5 on 2025-05-19 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticia', '0002_alter_noticia_parrafo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticia',
            name='Fecha_Publicacion',
            field=models.DateField(verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='Parrafo',
            field=models.TextField(max_length=10000, verbose_name='Contenido de la Noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='Titulo',
            field=models.CharField(max_length=40, unique=True, verbose_name='Título de la noticia'),
        ),
    ]
