# Generated by Django 5.2 on 2025-05-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticia', '0003_noticia_autor_alter_noticia_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='Titulo',
            field=models.CharField(max_length=400, unique=True, verbose_name='Título de la noticia'),
        ),
    ]
